### PR TITLE
Adding LION9 version of the pre-marshalling dataset including all LFA itrs

### PR DESCRIPTION
**Pull request by HerrKevin**
I have no idea what I am doing. Maybe this will work? :)

### CODE REVIEW

**Comment by larskotthoff** [comment]
Hi Kevin,

yes, you're doing this correctly :)

Should this be an amendment to the existing data set or a new data set? What are the changes compared to the version that's in aslib already?

**Comment by HerrKevin** [comment]
This version of the pre-marshalling dataset has:
* More instances; Now it includes instances from Caserta & Voß (2009) and Exposito et al. (2012) as well as an extra test set from a generator (https://bitbucket.org/eusorpb/cpmp-as)
* More features: we have generated more features based on Latent Feature Analysis (Malitsky & O'Sullivan 2014)

I have made it a new dataset for these reasons, but in the end it is just an extension of the old dataset. Perhaps we could have an area for "deprecated" datasets for people who want to do a comparison to an "old" dataset for some reason and that way the dataset doesn't dissapear.

**Comment by larskotthoff** [comment]
Hmm, sounds like it should be a new version of the existing data set to me. We do have the versioning and releases, so the old version definitely wouldn't be lost.

Is there any reason to keep the old version as a separate data set, i.e. are the two so different that you'd want to run selection and both and compare?

**Comment by HerrKevin** [comment]
I can't think of any reason that one would want to compare the two. OK, I will close this pull request and merge the 2015 version into the 2013 one, then create a new request.

**Comment by larskotthoff** [comment]
Ok thanks. You also could have added another commit (that moves the new dataset to the old) to this pull request.

**Pull request closed without merging**
