### PR TITLE
New scenario

### PR DESCRIPTION
**Pull request by WilliamRaynaut**
This is the openML metadataset that Bernd wanted me to add. I did my best to comply to the specs but don't really have the time to learn how to make that check_tool work atm.

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks. I ran the checker and there are a few problems:

- In the description, could you please use only spaces, not tabs?
- algorithm_runs.arff is not valid:
```
  row col   expected     actual
34658  -- 15 columns 14 columns
```

**Comment by WilliamRaynaut** [comment]
Ok, I edited the description and hopefully fixed algorithm_runs.arff.
Thanks for the check

**Comment by larskotthoff** [comment]
Thanks. I'm afraid I'm still getting errors with the check tool:

```
% Read ./algorithm_runs.arff
[ERROR]: The following performance data has missing values. Please impute all missing values.
312,1.0,1106,None,None,None,None,None,None,None,None,None,None,None,ok
```

**Comment by WilliamRaynaut** [comment]
Missing values removed in algorithm_runs.arff

**Comment by larskotthoff** [comment]
Thanks. More niggles I'm afraid -- you've set the cutoff times etc to "?". Please numbers there. They don't need to be 100% accurate, an upper bound is ok.

**Comment by WilliamRaynaut** [comment]
Values added, 3 days and 8g should be more than enough for any of those algorithms. You may want to update the format specifications, which state that "?" should be used when no cutoff was in place.

**Comment by larskotthoff** [comment]
Thanks again. The latest version of the format specification should already say that you have to use integer values. Where did you find the spec that says you can use a question mark?

The check tool found that instance 1115 has features and feature status, but no algorithm results. Did all algorithms crash on it?

**Comment by WilliamRaynaut** [comment]
The link on coseal website's aslib page points to https://github.com/coseal/aslib-spec/releases
I used the pdf in the zip sources V2 from there.

To remove all missing values from algorithm_runs.arff, I had to delete three runs, it is very possible that this is why 1115 is orphan. Should I remove it from the instances ?

**Comment by larskotthoff** [comment]
Ok, I've fixed the spec.

And yes please, remove instances that don't appear in all files.

**Comment by WilliamRaynaut** [comment]
1115 removed from feature_values and feature_runstatus

**Comment by larskotthoff** [comment]
Great, thanks again. Merging.

**Comment by larskotthoff** [comment]
@WilliamRaynaut Could you have a look at #9 please?

**Pull request merged**
