### PR TITLE
fixing missing repetition value/feature groups in PMA*2015

### PR DESCRIPTION
**Pull request by HerrKevin**
Fixing mistake pointed out by Pascal; also noticed that the three feature groups present in the train features weren't explicitly mentioned in the test features file. feature_runstatus_test.arff now has the necessary data and matches feature_runstatus.arff in its format.

### CODE REVIEW

**Comment by kerschke** [comment]
wait.. why is there now a 7th runstatus attribute level for the runstatus? Shouldn't `unknown` be a part of `other`?

**Comment by kerschke** [comment]
sorry.. my bad. it looks like we used that 7th level in the other scenarios as well. So thanks for fixing that :-)

**Comment by HerrKevin** [comment]
No problem! I'm not sure what it is for either, but the other ones use it too.

**Comment by kerschke** [comment]
I just checked the paper with the format specifications and they actually do not have that level either, so either the format paper is not up-to-date or the scenarios need to be fixed :-/
It looks like we'll have to fix one of the two..

**Pull request merged**
