### PR TITLE
Music dataset

### PR DESCRIPTION
**Pull request by larskotthoff**
This is the music dataset that we talked about at Dagstuhl. First draft, please check!

### CODE REVIEW

**Comment by mlindauer** [comment]
Interesting scenario. However, the data is weird.
We have ~4.7k instance features but only 32 instances.
Furthermore, these 32 instances have only 4 different feature vectors, i.e., 8 instances have always the same features.
So, I don't know what you would like to learn from such data.

btw: cv.arff is missing

**Comment by larskotthoff** [comment]
Yes, it's a bit weird. I didn't get any improvement over the single best...

BTW, I'm getting an error with your data check tool because the algorithm cutoff time is not a number.

I'll have a look at adding cv.arff.

**Comment by mlindauer** [comment]
> I didn't get any improvement over the single best...
That's not surprising for me if we have essentially only 4 data points.

Are the feature vectors correct?
Do we have really only 32 instances?

**Comment by larskotthoff** [comment]
Yes, there's really only 32 instances. I'll check the feature vectors, but they should be correct.

**Comment by mlindauer** [comment]
> but they should be correct.

If we have only 4 different feature vectors, I don't see the point of including this scenario in ASlib. What can we learn from 4 points in the feature space? For a somehow meaningful 10-fold cross validation, we would also need at least 10 different feature vectors.

**Pull request closed without merging**
