### PR TITLE
Add SAT2020-MAIN scenario

### PR DESCRIPTION
**Pull request by Theomat**
Hi,
@MarieNyst and I propose the addition of a scenario that includes the result  of the main track of the SAT 2020 competition.

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks! Could you also please specify how much memory was given to the algorithm runs, if available, and specify a cross-validation split file (cv.arff) for better reproducibility?

The scenario check tool says

    [ERROR]: Missing Features with status OK: TT7F-34-24B.cnf.

**Comment by Theomat** [comment]
There seems to be a small bug in the scenario checker tool line 161 in `coseal_reader.py`:
```python
        self.metainfo.features_cutoff_memory = description.get('algorithm_cutoff_memory')
```
should in fact be:
```python
        self.metainfo.algorithm_cutoff_memory = description.get('algorithm_cutoff_memory')
```
which causes the issue that the `algorithm_cutoff_memory` is always said to be missing.

**Comment by larskotthoff** [comment]
Thanks -- could you submit a PR for this as well please?

I'm still getting the error message about missing features with runstatus being ok.

**Comment by Theomat** [comment]
The scenario should pass the checker now.
It also seems that in the scenario tool checker, you do not check that all instances are included in the CV split.

**Comment by mlindauer** [comment]
Thank you for submitting the scenario.

> It also seems that in the scenario tool checker, you do not check that all instances are included in the CV split.

True. Happy to get another PR to fix this.

**Review by mlindauer — APPROVED** [review]

**Pull request merged**
