### PR TITLE
Adding a BNSL-2016 scenario

### PR DESCRIPTION
**Pull request by jwkangas**
This is an algorithm selection scenario on optimal Bayesian network structure learning, requested by reviewers of our recent paper (still under review). I'm new to using github so please let me know if I'm doing this right. Also please let me know if you have any questions on the scenario or any changes/additions that need to be made to the data.

-Kustaa

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks, the format itself is ok. I would recommend that you add a few things though:
- feature costs (if you measured them)
- citation.bib (saying "under review" is fine, or link to a version on arxiv if you have it)
- cv.arff with the splits that you used in your evaluation

Happy to merge once these points are clarified.

**Comment by jwkangas** [comment]
The requested files should now be in place. Please let me know if I need to make a new pull request for these changes or if they can be merged directly.

**Comment by larskotthoff** [comment]
Looks great, merging.

**Comment by jwkangas** [comment]
Thank you! We're happy to submit to ASlib.

**Comment by larskotthoff** [comment]
FYI, I've run some basic benchmarks to see what we can get with algorithm selection (in R, numbers are mean runtimes):

```
library(aslib)
library(llama)
library(parallelMap)

scenario.aslib = parseScenario("BNSL-2016")
scenario.llama = convertToLlamaCVFolds(scenario.aslib)

parallelStartMulticore()

mean(parscores(scenario.llama, vbs, 1))
[1] 219.8673
mean(parscores(scenario.llama, singleBest, 1))
[1] 1142.666

m.c = classify(makeLearner("classif.randomForest"), scenario.llama)
mean(parscores(scenario.llama, m.c, 1))
[1] 455.7224

m.r = regression(makeLearner("regr.randomForest"), scenario.llama)
mean(parscores(scenario.llama, m.r, 1))
[1] 363.6333

m.cp = classifyPairs(makeLearner("classif.randomForest"), scenario.llama)
mean(parscores(scenario.llama, m.cp, 1))
[1] 1753.732

m.rp = regressionPairs(makeLearner("regr.randomForest"), scenario.llama)
mean(parscores(scenario.llama, m.rp, 1))
[1] 378.7565
```

Not sure what's going on with the pairwise classification, but the performance for the regression models is very decent.

**Comment by mlindauer** [comment]
@larskotthoff Thanks for the numbers. Of course I was interested to compare it against my tool.
My (cost-sensitive) pairwise classification has a PAR1 score of 440. 

btw: I found an issue in the scenario:
The cv.arff was not correct. The first cv-fold has to be 1 and not 0. I fixed it by renaming fold 0 as 10.

**Pull request merged**
